<a href="https://colab.research.google.com/github/Barasinghaa/Deep_learning/blob/main/Word_embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Embedding

In [2]:
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [3]:
one_hot("nice food",30)

[29, 27]

In [4]:
vocab_size=30

encoded_reviews=[one_hot(d,vocab_size) for d in reviews]
encoded_reviews

[[29, 27],
 [11, 26],
 [1, 4],
 [22, 2, 13],
 [6, 5, 3],
 [17, 27],
 [17, 5, 21],
 [2, 27],
 [2, 11],
 [22, 25]]

In [6]:
max_length = 3
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[29 27  0]
 [11 26  0]
 [ 1  4  0]
 [22  2 13]
 [ 6  5  3]
 [17 27  0]
 [17  5 21]
 [ 2 27  0]
 [ 2 11  0]
 [22 25  0]]


In [7]:
embeded_vector_size = 5

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [8]:
X = padded_reviews
y = sentiment

In [9]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 3, 5)              150       
                                                                 
 flatten (Flatten)           (None, 15)                0         
                                                                 
 dense (Dense)               (None, 1)                 16        
                                                                 
Total params: 166
Trainable params: 166
Non-trainable params: 0
_________________________________________________________________
None


In [12]:
model.fit(X,y,epochs=50,verbose=0)

In [13]:
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 [==============================] - 0s 37ms/step - loss: 0.5568 - accuracy: 0.9000


0.8999999761581421

In [14]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [15]:
weights[5]

array([-0.01241656, -0.0237413 ,  0.0963422 ,  0.10087708, -0.05599612],
      dtype=float32)